"""Room, camera, robot and mission configuration.

Everything machine-specific lives in ``config/room*.json`` so no module
hard-codes a number that changes behavior. Load once with ``RoomConfig.load``;
all validation happens at load time so a bad config fails immediately and
loudly, not mid-episode.
"""
from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field, fields
from pathlib import Path
from typing import Any


class ConfigError(ValueError):
    """Raised when a room config is missing or inconsistent."""


def _need(data: dict, key: str, where: str) -> Any:
    if key not in data:
        raise ConfigError(f"{where}: missing required key '{key}'")
    return data[key]


def _num_list(value: Any, n_min: int, where: str, n_max: int | None = None) -> list[float]:
    if not isinstance(value, (list, tuple)) or len(value) < n_min:
        raise ConfigError(f"{where}: expected at least {n_min} numbers, got {value!r}")
    if n_max is not None and len(value) > n_max:
        raise ConfigError(f"{where}: expected at most {n_max} numbers, got {value!r}")
    out: list[float] = []
    for v in value:
        if not isinstance(v, (int, float)):
            raise ConfigError(f"{where}: {v!r} is not a number")
        out.append(float(v))
    return out


@dataclass
class CameraConfig:
    # "0" for the first USB camera, "/dev/videoN", an RTSP/HTTP URL, or a video file.
    source: str = "0"
    width: int = 1280
    height: int = 720
    # Optional ``calibrate.py intrinsics`` output; when set, frames are undistorted first.
    intrinsics: str = ""


@dataclass
class FloorConfig:
    # Room outline in image pixels. Obstacle candidates are only looked for inside it.
    polygon_px: list[list[float]] = field(default_factory=list)
    # Max CIE-Lab distance from the sampled floor color for a pixel to count as floor.
    lab_tolerance: float = 22.0
    # Optional empty-room reference frame; grayscale difference above this is not floor.
    background: str = ""
    bg_tolerance: float = 18.0
    # Slowly re-estimate the floor color while running (handles daylight drift).
    adapt: bool = False


@dataclass
class HomographyConfig:
    # >= 4 pixel/world correspondences of floor points, in the same order.
    image_points_px: list[list[float]] = field(default_factory=list)
    world_points_m: list[list[float]] = field(default_factory=list)


@dataclass
class GridConfig:
    cell_m: float = 0.05
    inflation_m: float = 0.22
    max_range_m: float = 5.5
    occupancy_threshold: float = 0.5   # probability above which a cell is an obstacle
    stale_s: float = 3.0               # a cell not seen for this long becomes unknown


@dataclass
class RoverConfig:
    footprint_radius_m: float = 0.18
    tag_id: int = 0
    tag_size_m: float = 0.10
    # Rotation between the tag's +y (printed "up") and the rover's forward axis.
    tag_yaw_offset_deg: float = 0.0
    # Pixels around the rover's footprint that are ignored as obstacles (body, shadow lip).
    rover_mask_extra_m: float = 0.08
    max_speed_mps: float = 0.6
    max_turn_deg_s: float = 120.0
    creep_speed_mps: float = 0.15
    tof_stop_m: float = 0.18           # mirror of the ESP32 reflex, laptop-side
    tof_slow_m: float = 0.35
    command_ttl_ms: int = 400


@dataclass
class TargetConfig:
    mode: str = "none"                 # none | tag | color
    tag_id: int = 1
    hsv_lo: list[int] = field(default_factory=lambda: [0, 120, 80])
    hsv_hi: list[int] = field(default_factory=lambda: [15, 255, 255])
    min_area_px: int = 200
    standoff_m: float = 1.0


@dataclass
class SyntheticConfig:
    """Frames generated by ``synthetic.py`` — lets the whole loop run without hardware."""

    px_per_m: float = 200.0
    drive_v_mps: float = 0.45
    drive_w_deg_s: float = 14.0


@dataclass
class RoomConfig:
    name: str = "room"
    width_m: float = 6.4
    height_m: float = 3.6
    camera: CameraConfig = field(default_factory=CameraConfig)
    floor: FloorConfig = field(default_factory=FloorConfig)
    homography: HomographyConfig = field(default_factory=HomographyConfig)
    grid: GridConfig = field(default_factory=GridConfig)
    rover: RoverConfig = field(default_factory=RoverConfig)
    target: TargetConfig = field(default_factory=TargetConfig)
    synthetic: SyntheticConfig = field(default_factory=SyntheticConfig)
    # name -> [x_m, y_m] or [x_m, y_m, yaw_deg]
    waypoints: dict[str, list[float]] = field(default_factory=dict)
    # route name -> ordered list of waypoint names
    routes: dict[str, list[str]] = field(default_factory=dict)
    # manually marked no-go circles: [x_m, y_m, radius_m]
    nogo: list[list[float]] = field(default_factory=list)

    # ------------------------------------------------------------------ load
    @classmethod
    def load(cls, path: str | Path) -> "RoomConfig":
        raw = json.loads(Path(path).read_text())
        return cls.from_dict(raw, where=str(path))

    @classmethod
    def from_dict(cls, data: dict, where: str = "config") -> "RoomConfig":
        cfg = cls(
            name=str(data.get("name", "room")),
            width_m=float(data.get("width_m", 6.4)),
            height_m=float(data.get("height_m", 3.6)),
        )
        for key, typ in (("camera", CameraConfig), ("floor", FloorConfig),
                         ("homography", HomographyConfig), ("grid", GridConfig),
                         ("rover", RoverConfig), ("target", TargetConfig),
                         ("synthetic", SyntheticConfig)):
            if key in data:
                cfg.__dict__[key] = _section(typ, data[key], f"{where}.{key}")
        cfg.waypoints = _waypoints(data.get("waypoints", {}), where)
        cfg.routes = dict(data.get("routes", {}))
        cfg.nogo = [
            _num_list(v, 3, f"{where}.nogo[{i}]", 3) for i, v in enumerate(data.get("nogo", []))
        ]
        cfg.validate(where)
        return cfg

    def validate(self, where: str = "config") -> None:
        if self.width_m <= 0 or self.height_m <= 0:
            raise ConfigError(f"{where}: room must have positive width_m/height_m")
        h = self.homography
        if len(h.image_points_px) != len(h.world_points_m):
            raise ConfigError(
                f"{where}.homography: {len(h.image_points_px)} image points but "
                f"{len(h.world_points_m)} world points"
            )
        if len(h.image_points_px) < 4:
            raise ConfigError(f"{where}.homography: need >= 4 correspondences, "
                              f"got {len(h.image_points_px)} (run: calibrate.py floor)")
        for i, p in enumerate(h.image_points_px):
            if len(p) != 2:
                raise ConfigError(f"{where}.homography.image_points_px[{i}] must be [x, y]")
        for i, p in enumerate(h.world_points_m):
            if len(p) != 2:
                raise ConfigError(f"{where}.homography.world_points_m[{i}] must be [x, y]")
        if len(self.floor.polygon_px) < 3:
            raise ConfigError(f"{where}.floor.polygon_px: need >= 3 points "
                              f"(run: calibrate.py floor)")
        r = self.rover
        if not (0.02 <= r.footprint_radius_m <= 0.5):
            raise ConfigError(f"{where}.rover.footprint_radius_m out of range: "
                              f"{r.footprint_radius_m}")
        if r.tof_stop_m >= r.tof_slow_m:
            raise ConfigError(f"{where}.rover: tof_stop_m must be < tof_slow_m")
        if r.tag_size_m <= 0:
            raise ConfigError(f"{where}.rover.tag_size_m must be positive")
        if self.target.mode not in ("none", "tag", "color"):
            raise ConfigError(f"{where}.target.mode must be none|tag|color")
        for name, wp in self.waypoints.items():
            if not (0 <= wp[0] <= self.width_m and 0 <= wp[1] <= self.height_m):
                raise ConfigError(f"{where}.waypoints.{name}: {wp[:2]} outside the room")
        for route, names in self.routes.items():
            for n in names:
                if n not in self.waypoints:
                    raise ConfigError(f"{where}.routes.{route}: unknown waypoint '{n}'")

    # ------------------------------------------------------------- accessors
    def waypoint(self, name: str) -> tuple[float, float, float | None]:
        if name not in self.waypoints:
            raise ConfigError(f"unknown waypoint '{name}'")
        wp = self.waypoints[name]
        return wp[0], wp[1], (wp[2] if len(wp) > 2 else None)

    def to_dict(self) -> dict:
        out = asdict(self)
        # Native JSON types for the config round-trip.
        return json.loads(json.dumps(out))

    def save(self, path: str | Path) -> None:
        Path(path).write_text(json.dumps(self.to_dict(), indent=2) + "\n")


def _section(typ: type, data: dict, where: str):
    if not isinstance(data, dict):
        raise ConfigError(f"{where}: expected an object")
    kwargs: dict[str, Any] = {}
    for f in fields(typ):
        if f.name in data:
            kwargs[f.name] = data[f.name]
    obj = typ(**kwargs)
    # Type coercion + per-field validation for the numeric knobs.
    for f in fields(typ):
        v = getattr(obj, f.name)
        if isinstance(v, (int, float)) and not isinstance(v, bool):
            setattr(obj, f.name, float(v) if isinstance(v, float) else v)
    return obj


def _waypoints(data: dict, where: str) -> dict[str, list[float]]:
    if not isinstance(data, dict):
        raise ConfigError(f"{where}.waypoints: expected an object of name -> [x, y]")
    out: dict[str, list[float]] = {}
    for name, v in data.items():
        out[name] = _num_list(v, 2, f"{where}.waypoints.{name}", 3)
    return out
